language: java
sudo: required
#cache:
#  directories:
#    - $HOME/.m2
jdk:
  - oraclejdk8

script:
  - cd eventeando-BE
  - gradle clean
  - gradle build

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
    app: eventeando
